#!/usr/bin/tclsh
#Purpose: Error Handling in TCL
#Version: 1.0
#Created Date: Fri Feb 24 23:16:46 IST 2023
#Modified Date:
#Author: Ashok Kumar 
#START #

#Error syntax:
#error message info code
#In the above error command syntax, message is the error message, info is set in the global variable errorInfo and code is set in the global variable errorCode.
#
#Catch Syntax:
#catch script resultVarName
#In the above catch command syntax, script is the code to be executed, resultVarName is variable that holds the error or the result. The catch command returns 0 if there is no error, and 1 if there is an error.
#
#

proc Div {a b} {
	if {$b == 0} {
		error "Error generated by error" "Info string for error" 401
	} else {
		return [expr $a/$b]
	}
}

if {[catch {puts "Result = [Div 10 0]"} errmesg]} {
	puts "ErrorMsg: $errmesg"
	puts "ErrorCode: $errorCode"
	puts "ErrorInfo: \n$errorInfo\n"
}
if {[catch {puts "Result = [Div 10 2]"} errmesg]} {
	puts "ErrorMsg: $errmesg"
	puts "ErrorCode: $errorCode"
	puts "ErrorInfo: \n$errorInfo\n"
}

# END #
